import React, { createContext, useContext, useEffect, useMemo, useState } from 'react';

type Language = 'en' | 'es';

type Translations = Record<string, string>;

const translationMap: Record<Language, Translations> = {
  en: {
    'brand.title': 'Anxiety Companion',
    'brand.appName': 'Tranquiloo',
    'nav.dashboard': 'Dashboard',
    'nav.chat': 'Chat',
    'nav.chatHistory': 'Chat History',
    'nav.analytics': 'Analytics',
    'nav.appointments': 'My Appointments',
    'nav.treatment': 'Track Outcomes/Treatment',
    'nav.contactTherapist': 'Contact Therapist',
    'nav.settings': 'Settings',
    'nav.help': 'Help',
    'nav.share': 'Share App',
    'nav.logout': 'Log Out',
    'share.title': 'Share App',
    'share.description': 'Check out this amazing mental health companion app!',
    'share.copiedTitle': 'Link copied!',
    'share.copiedDesc': 'App link has been copied to clipboard.',
    'share.error': 'Unable to share right now. Link copied to clipboard instead.',
    'mobile.title.analytics': 'Analytics',
    'mobile.title.chatHistory': 'Chat History',
    'mobile.title.chat': 'Chat',
    'mobile.title.treatment': 'Track Treatment',
    'mobile.title.therapist': 'Find Therapist',
    'mobile.title.settings': 'Settings',
    'mobile.title.help': 'Help',
    'mobile.title.dashboard': 'Tranquiloo',
    'lang.english': 'English',
    'lang.spanish': 'Español',
    'lang.switch': 'Language',
    'nav.share': 'Share App',
    'nav.logout': 'Log Out',
    // Auth common
    'auth.backHome': 'Back to home',
    'auth.welcomeBack': 'Welcome Back',
    'auth.createAccount': 'Create Account',
    'auth.resetPassword': 'Reset Password',
    'auth.resetSubtitle': "We'll send you instructions to reset your password",
    'auth.emailLabel': 'Email Address',
    'auth.emailPlaceholder': 'Enter your email',
    'auth.emailHint': 'Enter the email address associated with your account',
    'auth.sendReset': 'Send Reset Link',
    'auth.sending': 'Sending...',
    'auth.rememberPassword': 'Remember your password?',
    'auth.tagline': 'Your mental health journey starts here',
    'auth.communityTagline': 'Join our mental health community',
    'auth.roleQuestion': 'I am registering as:',
    'auth.patientRole': 'Patient',
    'auth.therapistRole': 'Therapist',
    'auth.haveAccount': 'Already have an account?',
    'auth.passwordMismatch': 'Passwords do not match',
    'auth.networkError': 'Network error. Please try again.',
    'auth.createJourney': 'Create your account to start your journey',
    'auth.resetInstructions': 'Enter your email to reset your password',
    'auth.continueGoogle': 'Continue with Google',
    'auth.email': 'Email address',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm password',
    'auth.signIn': 'Sign In',
    'auth.signUp': 'Sign Up',
    'auth.createAccountCta': "Don't have an account? Sign up",
    'auth.orEmail': 'Or continue with email',
    'auth.therapistPortal': 'Therapist Portal',
    'auth.areTherapist': 'Are you a therapist? Click here',
    'auth.noAccount': "Don't have an account?",
    'auth.forgotPassword': 'Forgot your password?',
    'auth.patientJourney': 'Sign in to continue your journey',
    'auth.therapistJourney': 'Sign in to access your professional dashboard',
    'auth.googleDisclaimer': 'We are working toward HIPAA readiness; please avoid sharing PHI.',
    'auth.firstName': 'First name',
    'auth.lastName': 'Last name',
    'auth.backToSignIn': 'Back to Sign In',
    'auth.checkEmail': 'Check Your Email',
    'auth.resetEmailSent': "If an account exists with {email}, we've sent password reset instructions.",
    'auth.resetEmailBody': 'Check your email and click the reset link to create a new password. The link expires in 1 hour.',
    'auth.invalidCredentials': 'Invalid email or password',
    'auth.verifyEmailFirst': 'Please verify your email address first. Check your inbox for the verification link.',
    // Contact therapist
    'contact.title': 'Contact Therapist',
    'contact.subtitle': 'Connect with your therapist or download your anxiety data for professional consultation',
    'contact.question': 'Do you currently have a therapist?',
    'contact.questionDesc': 'If you have a therapist, we can connect your account so they can track your progress and provide better support.',
    'contact.optionYes': "Yes, I have a therapist I'd like to connect",
    'contact.optionYesDesc': 'Send them a secure request to review your progress.',
    'contact.optionNo': "No, I don't have a therapist",
    'contact.optionNoDesc': 'Download your data or explore professional options.',
    'contact.connectTitle': 'Connect with Your Therapist',
    'contact.connectDesc': 'Enter your therapist’s email to send them a connection request',
    'contact.emailLabel': 'Therapist Email',
    'contact.emailPlaceholder': 'therapist@example.com',
    'contact.messageLabel': 'Message (Optional)',
    'contact.messagePlaceholder': 'Let your therapist know about your current concerns...',
    'contact.sendRequest': 'Send Connection Request',
    'contact.connecting': 'Connecting...',
    'contact.back': 'Back',
    'contact.selfGuidedTitle': "You're in self-guided mode",
    'contact.selfGuidedDesc': 'Continue using the app for anxiety management. Consider connecting with a therapist for professional support.',
    'contact.downloadTitle': 'Download Your Anxiety Data',
    'contact.downloadDesc': 'Get your complete anxiety tracking data and conversation summaries to share with a mental health professional',
    'contact.packageTitle': 'Your data package includes:',
    'contact.packageItem1': 'Complete anxiety tracking history and trends',
    'contact.packageItem2': 'Conversation summaries with AI companion',
    'contact.packageItem3': 'Trigger analysis and patterns',
    'contact.packageItem4': 'Goal progress and intervention outcomes',
    'contact.packageItem5': 'Clinical assessment results',
    'contact.downloadCta': 'Download My Anxiety Data',
    'contact.backOptions': 'Back to Options',
    'contact.readyTitle': 'Ready to Find a Therapist?',
    'contact.readyDesc': 'Professional therapy can significantly improve your anxiety management journey',
    'contact.benefitsTitle': 'Benefits of Professional Therapy:',
    'contact.benefit1': 'Personalized treatment plans based on your specific needs',
    'contact.benefit2': 'Evidence-based therapeutic approaches (CBT, DBT, etc.)',
    'contact.benefit3': 'Professional crisis support and intervention',
    'contact.benefit4': 'Medication management when appropriate',
    'contact.benefit5': 'Long-term recovery and coping strategies',
    'contact.findTherapist': 'Find Therapists Near Me',
    'contact.downloadStarted': 'Download Started',
    'contact.downloadStartedDesc': 'Downloading your anxiety data and conversation summary...',
    'contact.downloadError': 'Download Error',
    'contact.downloadErrorDesc': 'Failed to download anxiety data',
    'contact.emailRequired': 'Email required',
    'contact.emailRequiredDesc': "Please enter your therapist's email address",
    'contact.requestSent': 'Connection Request Sent',
    'contact.requestSentDesc': 'Your therapist will receive a notification to approve the connection',
    'contact.requestError': 'Connection Error',
    'contact.requestErrorDesc': 'Failed to connect with therapist. Please try again.',
    'contact.emergencyTitle': 'Emergency Resources',
    'contact.emergency1': 'National Suicide Prevention Lifeline',
    'contact.emergency1Desc': '24/7 crisis support',
    'contact.emergency2': 'Crisis Text Line',
    'contact.emergency2Desc': 'Text support available 24/7',
    'contact.emergency3': 'SAMHSA National Helpline',
    'contact.emergency3Desc': 'Treatment referral and information',
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.heroTitle': 'Anxiety Guardian',
    'dashboard.heroSubtitle': 'Your AI-powered anxiety support companion. Get personalized guidance, track your progress, and find peace of mind whenever you need it.',
    'dashboard.startChatting': 'Start Chatting',
    'dashboard.takeAssessment': 'Take Assessment',
    'dashboard.trackTreatment': 'Track Outcomes/Treatment',
    'dashboard.analytics': 'Analytics',
    'dashboard.feature.safe': 'Safe & Private',
    'dashboard.feature.safeDesc': 'Your conversations are completely private and secure',
    'dashboard.feature.support': '24/7 Support',
    'dashboard.feature.supportDesc': 'Always available when you need someone to talk to',
    'dashboard.feature.personalized': 'Personalized Care',
    'dashboard.feature.personalizedDesc': 'Tailored support based on your unique needs',
    'dashboard.footer.rights': 'All rights reserved.',
    'dashboard.footer.privacy': 'Privacy Policy',
    'dashboard.footer.terms': 'Terms of Service',
    'dashboard.footer.contact': 'Contact Us',
    'dashboard.footer.disclaimer': 'This app is not a substitute for professional medical advice, diagnosis, or treatment. Always seek the advice of your physician or other qualified health provider with any questions you may have regarding a medical condition.',
    'dashboard.footer.version': 'Version',
    // Settings
    'settings.title': 'Settings',
    'settings.subtitle': 'Customize your experience and manage your preferences.',
    'settings.account': 'Account',
    'settings.accountDesc': 'Manage your account information and settings.',
    'settings.currentEmail': 'Current Email',
    'settings.notSignedIn': 'Not signed in',
    'settings.patientCode': 'Your Patient Code',
    'settings.copy': 'Copy',
    'settings.codeCopied': 'Patient code copied to clipboard',
    'settings.shareCodeHint': 'Share this code with your therapist along with your email address so they can access your analytics and treatment data.',
    'settings.newEmail': 'New Email Address',
    'settings.newEmailPlaceholder': 'Enter new email address',
    'settings.updateEmail': 'Update Email',
    'settings.updating': 'Updating...',
    'settings.emailErrorTitle': 'Error',
    'settings.emailErrorDesc': 'Please enter a different email address',
    'settings.emailUpdateError': 'Error updating email',
    'settings.emailUpdateErrorDesc': 'Failed to update email',
    'settings.emailRequestedTitle': 'Email update requested',
    'settings.emailRequestedDesc': 'Check both your old and new email addresses for confirmation links to complete the change.',
    'settings.logout': 'Log Out',
    'settings.loggingOut': 'Logging out...',
    'settings.logoutSuccess': 'Logged out successfully',
    'settings.logoutSuccessDesc': 'You have been signed out of your account.',
    'settings.logoutError': 'Error logging out',
    'settings.logoutErrorDesc': 'Failed to log out',
    'settings.voiceLanguage': 'Voice & Language',
    'settings.voiceLanguageDesc': 'Configure how the AI speaks and responds to you.',
    'settings.languageLabel': 'Language',
    'settings.languagePlaceholder': 'Select language',
    'settings.voiceResponses': 'Voice Responses',
    'settings.voiceResponsesDesc': 'Enable AI to speak responses aloud',
    'settings.voiceInterruption': 'Voice Interruption',
    'settings.voiceInterruptionDesc': 'Allow interrupting AI by speaking',
    'settings.privacy': 'Privacy & Data',
    'settings.privacyDesc': 'Control how your data is stored and used.',
    'settings.localStorage': 'Local Storage Only',
    'settings.localStorageDesc': 'Keep all data on your device',
    'settings.analytics': 'Allow Analytics',
    'settings.analyticsDesc': 'Help us improve by sharing anonymized usage',
    'settings.dailyCheckIns': 'Daily Check-ins',
    'settings.dailyCheckInsDesc': 'Receive daily mood and anxiety prompts',
    'settings.breathingReminders': 'Breathing Reminders',
    'settings.breathingRemindersDesc': 'Get reminders for breathing exercises',
    // Therapist portal (light)
    'therapistPortal.title': 'Therapist Portal',
    'therapistPortal.subtitle': "Enter your email to access your patients' progress data",
    'therapistPortal.emailLabel': 'Email Address',
    'therapistPortal.emailPlaceholder': 'dr.smith@example.com',
    'therapistPortal.access': 'Access Portal',
    'therapistPortal.verifying': 'Verifying...',
    'therapistPortal.demoNote': 'Demo Note:',
    'therapistPortal.demoBody': 'Enter any email address that patients have used to connect with you. This portal shows the same analytics and outcomes that patients see in their app.',
    'therapistPortal.emailRequired': 'Email Required',
    'therapistPortal.emailRequiredDesc': 'Please enter your email address',
    'therapistPortal.accessGranted': 'Access Granted',
    'therapistPortal.welcome': 'Welcome to the therapist portal',
    'therapistPortal.errorTitle': 'Error',
    'therapistPortal.errorDesc': 'Failed to verify therapist access',
    'therapistPortal.searchRequired': 'Search Required',
    'therapistPortal.searchRequiredDesc': "Please enter a patient's email or 6-digit code",
    'therapistPortal.noPatients': 'No Patients Found',
    'therapistPortal.noPatientsDesc': 'No patients found with the provided search criteria',
    'therapistPortal.searchComplete': 'Search Complete',
    'therapistPortal.searchError': 'Failed to search for patients',
    // Notifications
    'notifications.title': 'Notifications',
    'notifications.back': 'Back to Dashboard',
    'notifications.new': 'new',
    'notifications.markAll': 'Mark all as read',
    'notifications.emptyTitle': 'No notifications',
    'notifications.emptyDesc': "You're all caught up! Check back later for updates.",
    'notifications.markRead': 'Mark as read',
    'notifications.type.anxiety': 'Anxiety Level Alert',
    'notifications.type.treatment': 'Treatment Update',
    'notifications.type.reminder': 'Reminder',
    'notifications.type.achievement': 'Achievement',
    'notifications.action.chat': 'Talk to AI Companion',
    'notifications.action.track': 'Track Your Mood',
    'notifications.action.progress': 'View Progress',
    'notifications.action.chatHistory': 'Open Chat History',
    'notifications.action.reschedule': 'Reschedule',
    'notifications.action.view': 'View details',
    'notifications.msg.anxiety': 'Your anxiety levels have been elevated for the past 3 days. Consider practicing breathing exercises or talking to your therapist.',
    'notifications.msg.achievement': "Great job! You've completed 7 consecutive days of mood tracking. Keep up the good work!",
    'notifications.msg.reminder': "You have a therapy session scheduled for tomorrow at 2:00 PM. Don't forget to prepare your notes.",
    'notifications.msg.treatment': 'Time for your weekly mental health check-in. How are you feeling this week?',
    // Help
    'help.title': 'Help Center',
    'help.faqTitle': 'Frequently Asked Questions',
    'help.faqDesc': 'Find answers to common questions about using Anxiety Companion',
    'help.q1': 'How does the AI companion work?',
    'help.a1': 'The AI companion uses advanced natural language processing to provide personalized support for anxiety management. It can engage in conversations, offer coping strategies, and help you track your emotional well-being.',
    'help.q2': 'Is my data private and secure?',
    'help.a2': 'Yes, your privacy is our top priority. All conversations and personal data are encrypted and stored securely. You have full control over your data.',
    'help.q3': 'Can I use this app without a therapist?',
    'help.a3': 'The app can be used independently for daily anxiety management, though we recommend consulting a mental health professional for comprehensive care.',
    'help.contactTitle': 'Contact Support',
    'help.contactDesc': "Can't find what you're looking for? Reach out to our support team.",
    'help.contactBody': "If you have questions that aren't answered in our FAQ, please contact our support team. We're here to help and typically respond within 24 hours.",
    'help.contactEmailLabel': 'Email',
    'help.contactEmail': 'support@anxietycompanion.com',
    // Support page (about/help)
    'support.title': 'Support Center',
    'support.subtitle': 'Get help with Tranquiloo and mental health resources',
    'support.backSettings': 'Back to Settings',
    'support.contactTeam': 'Contact Our Support Team',
    'support.contactBody': 'Our dedicated support team is here to help you with any questions, technical issues, or concerns about using Tranquiloo. We strive to provide timely, helpful responses to ensure you have the best possible experience.',
    'support.emailSupport': 'Email Support',
    'support.emailDesc': "Send us a detailed message and we'll get back to you within 24 hours.",
    'support.emailCta': 'Send Email',
    'support.phoneSupport': 'Phone Support',
    'support.phoneDesc': 'Speak directly with our support team for immediate assistance.',
    'support.callNow': 'Call Now',
    'support.textSupport': 'Text Message Support',
    'support.textDesc': 'Send us a text message for quick questions or non-urgent issues.',
    'support.textAvailability': 'Available 24/7 for non-emergency support',
    'support.crisisTitle': 'Crisis Support & Emergency Resources',
    'support.crisisLead': "If you're in crisis or having thoughts of self-harm:",
    'support.nationalResources': 'National Resources',
    'support.onlineResources': 'Online Resources',
    'support.faqTitle': 'Frequently Asked Questions',
    'support.faq1.q': 'How do I reset my password?',
    'support.faq1.a': "Go to the login page and click \"Forgot Password\". Enter your email address and we'll send you a secure link to reset your password.",
    'support.faq2.q': 'Is my data secure and private?',
    'support.faq2.a': 'We are working toward full compliance and use encryption to protect your personal health information. See our Privacy Policy for details.',
    'support.faq3.q': 'Can I export my conversation history?',
    'support.faq3.a': 'You can download your conversation summaries and analytics data from the Analytics and Treatment Resources pages.',
    'support.faq4.q': 'How accurate is the AI anxiety analysis?',
    'support.faq4.a': 'Our AI follows clinical anxiety assessment frameworks, but it complements—not replaces—professional care. Consult healthcare providers for clinical decisions.',
    'support.faq5.q': 'Can I use Tranquiloo with my therapist?',
    'support.faq5.a': 'Yes. You can share analytics and progress reports with your therapist using the “Share with Therapist” feature.',
    'support.faq6.q': 'How can my therapist access my progress data?',
    'support.faq6.a': 'After connecting your therapist in the app, they can access their dedicated portal to view real-time analytics and weekly reports.',
    // Therapist dashboard / patient directory
    'therapistDashboard.patientDirectory': 'Patient Directory',
    'therapistDashboard.patientDirectoryDesc': 'All your accepted patients ({count} total)',
    'therapistDashboard.searchPlaceholder': 'Search by name, email, or patient code...',
    'therapistDashboard.loadingPatients': 'Loading patient directory...',
    'therapistDashboard.noPatients': 'No patients yet',
    'therapistDashboard.noPatientsSearch': 'No patients found matching your search',
    'therapistDashboard.active': 'Active',
    'therapistDashboard.sharingReports': 'Sharing Reports',
    'therapistDashboard.email': 'Email',
    'therapistDashboard.patientCode': 'Patient Code',
    'therapistDashboard.phone': 'Phone',
    'therapistDashboard.gender': 'Gender',
    'therapistDashboard.age': 'Age',
    'therapistDashboard.connected': 'Connected',
    'therapistDashboard.years': 'years',
    'therapistDashboard.downloads.title': 'Download Activity Trends',
    'therapistDashboard.downloads.noneTitle': 'No Download History Yet',
    'therapistDashboard.downloads.noneDesc': 'Your download activity will appear here once you start exporting reports, charts, and analytics data. Each download will be tracked with detailed insights.',
    'therapistDashboard.downloads.total': 'Total Downloads',
    'therapistDashboard.downloads.totalData': 'Total Data',
    'therapistDashboard.downloads.thisWeek': 'This Week',
    'therapistDashboard.downloads.avgSize': 'Avg Size',
    'therapistDashboard.downloads.activity': 'Download Activity',
    'therapistDashboard.downloads.category': 'Download Category Mix',
    'therapistDashboard.downloads.types.analytics': 'Analytics',
    'therapistDashboard.downloads.types.reports': 'Reports',
    'therapistDashboard.downloads.types.summaries': 'Summaries',
    'therapistDashboard.downloads.types.exports': 'Exports',
    'therapistDashboard.range.allTime': 'All time',
    'therapistDashboard.range.select': 'Select range',
    'therapistDashboard.range.label': 'Date range',
    'therapistDashboard.range.apply': 'Apply',
    'therapistDashboard.range.clear': 'Clear',
    // Analytics header
    'analytics.header.title': 'Analytics Dashboard',
    'analytics.header.data': 'Showing data from {count} anxiety analysis sessions',
    'analytics.header.empty': 'No data yet - start chatting to see analytics',
    'analytics.header.downloadHistory': 'Download History',
    'analytics.header.downloadSummary': 'Download Conversation Summary',
    'analytics.header.shareTherapist': 'Share with Therapist',
    'analytics.header.viewTreatment': 'View Treatment',
    'analytics.header.realtime': 'Real-time data',
    // Analytics metrics
    'analytics.metrics.totalSessions': 'Total Sessions',
    'analytics.metrics.averageAnxiety': 'Average Anxiety',
    'analytics.metrics.mostCommonTrigger': 'Most Common Trigger',
    'analytics.metrics.noTriggers': 'No triggers recorded',
    'analytics.metrics.treatmentProgress': 'Treatment Progress',
    'analytics.metrics.progressImproving': 'Improving',
    // Analytics empty
    'analytics.empty.title': 'No Analytics Data Yet',
    'analytics.empty.desc': 'Start chatting with your AI companion to generate anxiety analytics data.',
    'analytics.empty.start': 'Start Chatting',
    // Analytics charts
    'analytics.trends.title': 'Weekly Anxiety Type Trends',
    'analytics.trends.none': 'No trend data available yet',
    'analytics.trends.work': 'Work/Career',
    'analytics.trends.social': 'Social',
    'analytics.trends.health': 'Health',
    'analytics.trends.financial': 'Financial',
    'analytics.trends.relationships': 'Relationships',
    'analytics.trends.future': 'Future/Uncertainty',
    'analytics.trends.family': 'Family',
    'analytics.triggers.title': 'Trigger Analysis',
    'analytics.triggers.total': 'Total entries: {count}',
    'analytics.triggers.trigger': 'Trigger',
    'analytics.triggers.count': 'Count',
    'analytics.triggers.avgSeverity': 'Avg severity',
    'analytics.triggers.trend': 'Trend',
    'analytics.triggers.related': 'Related triggers',
    'analytics.triggers.why': 'Why it happens',
    'analytics.triggers.description': 'Description',
    'analytics.triggers.evidence': 'Clinical Evidence',
    'analytics.triggers.trendLabel': 'Trend',
    'analytics.triggers.recalledContext': 'Recalled Context',
    'analytics.triggers.aggravators': 'Aggravating Factors',
    'analytics.triggers.impact': 'Impact/Avoidance',
    'analytics.triggers.lastOccurrence': 'Last Occurrence',
    'analytics.triggers.relatedPatterns': 'Related Trigger Patterns',
    // Anxiety tracker
    'analytics.tracker.title': 'Your Anxiety Analytics & Tracking',
    'analytics.tracker.emptyTitle': 'Anxiety Analytics & Tracking',
    'analytics.tracker.emptyDesc': 'Start chatting to see your anxiety analytics and intervention tracking.',
    'analytics.tracker.startChat': 'Start Chat Session',
    'analytics.tracker.avgAnxiety': 'Avg Anxiety',
    'analytics.tracker.avgGad7': 'Avg GAD-7',
    'analytics.tracker.sessions': 'Sessions',
    'analytics.tracker.trend': 'Trend',
    'analytics.tracker.mostEffective': 'Most Effective Interventions for You:',
    'analytics.tracker.effectiveness': 'effectiveness',
    'analytics.tracker.used': 'Used {count}x',
    'analytics.tracker.recentProgress': 'Your Recent Progress:',
    'analytics.tracker.progressImproving': '🎉 Great progress! Your anxiety levels have been decreasing. Keep using the interventions that work best for you.',
    'analytics.tracker.progressStable': '📊 Your anxiety levels are stable. Consider trying new interventions or increasing the frequency of current ones.',
    'analytics.tracker.progressWorsening': '🤗 Your anxiety levels have increased recently. This is normal - consider reaching out for additional support or trying crisis interventions.',
    // Treatment outcomes
    'analytics.outcomes.title': 'Treatment Outcomes',
    'analytics.outcomes.emptyDesc': 'Start tracking your anxiety to see treatment outcomes and trends.',
    'analytics.outcomes.anxietyLevel': 'Anxiety Level',
    // Monthly charts
    'analytics.monthly.title': 'Monthly Anxiety Trends by Category',
    'analytics.monthly.none': 'Add more sessions to see monthly trends.',
    // Chat history
    'chatHistory.title': 'Chat History',
    'chatHistory.subtitle': 'Review your previous conversations and anxiety interventions',
    'chatHistory.recentConversations': 'Recent Conversations',
    'chatHistory.sessionsDesc': 'Your chat sessions with AI companions',
    'chatHistory.analyticsTitle': 'Anxiety Analyses',
    'chatHistory.analyticsDesc': 'AI-generated analyses from your chats',
    'chatHistory.low': 'Low',
    'chatHistory.moderate': 'Moderate',
    'chatHistory.high': 'High',
    'chatHistory.noSessions': 'No chat sessions yet',
    'chatHistory.noSessionsDesc': 'Start a conversation to see your history here',
    'chatHistory.untitled': 'Untitled Chat',
    'chatHistory.viewConversation': 'View Conversation',
    'chatHistory.anxietyLevel': 'Anxiety Level',
    'chatHistory.interventions': 'Anxiety Interventions',
    'chatHistory.interventionsDesc': 'AI-powered anxiety analysis and coping strategies',
    'chatHistory.noAnalyses': 'No anxiety analyses yet',
    'chatHistory.noAnalysesDesc': 'Chat with our AI companions to receive personalized support',
    // Appointments
    'appointments.back': 'Back',
    'appointments.title': 'My Appointments',
    'appointments.subtitle': 'Schedule and manage therapy sessions',
    // Goals
    'analytics.goals.title': 'Goal Progress Overview',
    'analytics.goals.emptyTitle': 'No Goals Set Yet',
    'analytics.goals.emptyDesc': 'Start by creating goals to track your progress and see analytics.',
    'analytics.goals.total': 'Goals',
    'analytics.goals.completed': 'Completed',
    'analytics.goals.inProgress': 'In progress',
    'analytics.goals.avgScore': 'Avg score',
    'analytics.goals.adherence': 'Adherence',
    'analytics.goals.history': 'Progress history',
    'analytics.goals.category': 'Category',
    'analytics.goals.badge.completed': 'Completed',
    'analytics.goals.badge.good': 'Good progress',
    'analytics.goals.badge.started': 'Getting started',
    'analytics.goals.badge.new': 'New goal',
    'analytics.goals.progressLabel': 'Progress',
    'analytics.goals.scoreLabel': 'Score',
    // Treatment outcomes charts
    'analytics.outcomes.trendTitle': 'Average Anxiety Level Trends',
    'analytics.outcomes.trendEmptyTitle': 'No trend data available yet',
    'analytics.outcomes.trendEmptyDesc': 'Start tracking your anxiety levels to see progress trends',
    'analytics.outcomes.weeklyTitle': 'Weekly Treatment Outcomes',
    'analytics.outcomes.avgAnxiety': 'Avg Anxiety',
    'analytics.outcomes.trendLabel': 'Trend',
    'analytics.outcomes.treatmentEffectiveness': 'Treatment effectiveness',
    // Therapist auth
    'therapist.title.signin': 'Professional Portal',
    'therapist.title.signup': 'Join Our Professional Network',
    'therapist.subtitle.signin': 'Sign in to access your patient management dashboard',
    'therapist.subtitle.signup': 'Create your professional account to start connecting with patients',
    'therapist.immediateAccess': 'Immediate Access',
    'therapist.immediateAccess.desc': 'You can start using the therapist dashboard right away while we verify your license in the background',
    'therapist.licenseNumber': 'License number',
    'therapist.specialty': 'Specialty',
    'therapist.yearsExperience': 'Years of experience',
    'therapist.applyNow': "Don't have a professional account? Apply now",
  },
  es: {
    'brand.title': 'Compañero de Ansiedad',
    'brand.appName': 'Tranquiloo',
    'nav.dashboard': 'Panel',
    'nav.chat': 'Chat',
    'nav.chatHistory': 'Historial de chat',
    'nav.analytics': 'Analítica',
    'nav.appointments': 'Mis Citas',
    'nav.treatment': 'Seguimiento y Tratamiento',
    'nav.contactTherapist': 'Contactar terapeuta',
    'nav.settings': 'Configuración',
    'nav.help': 'Ayuda',
    'mobile.title.analytics': 'Analítica',
    'mobile.title.chatHistory': 'Historial de chat',
    'mobile.title.chat': 'Chat',
    'mobile.title.treatment': 'Seguimiento',
    'mobile.title.therapist': 'Encontrar terapeuta',
    'mobile.title.settings': 'Configuración',
    'mobile.title.help': 'Ayuda',
    'mobile.title.dashboard': 'Tranquiloo',
    'lang.english': 'English',
    'lang.spanish': 'Español',
    'lang.switch': 'Idioma',
    'nav.share': 'Compartir app',
    'nav.logout': 'Cerrar sesión',
    'share.title': 'Compartir app',
    'share.description': 'Descubre esta increíble app de acompañamiento en salud mental.',
    'share.copiedTitle': 'Enlace copiado',
    'share.copiedDesc': 'El enlace de la app se copió al portapapeles.',
    'share.error': 'No se pudo compartir ahora. Enlace copiado al portapapeles.',
    // Auth common
    'auth.backHome': 'Volver al inicio',
    'auth.welcomeBack': 'Bienvenido de nuevo',
    'auth.createAccount': 'Crear cuenta',
    'auth.resetPassword': 'Restablecer contraseña',
    'auth.resetSubtitle': 'Te enviaremos instrucciones para restablecer tu contraseña',
    'auth.emailLabel': 'Correo electrónico',
    'auth.emailPlaceholder': 'Ingresa tu correo',
    'auth.emailHint': 'Ingresa el correo asociado a tu cuenta',
    'auth.sendReset': 'Enviar enlace',
    'auth.sending': 'Enviando...',
    'auth.rememberPassword': '¿Recordaste tu contraseña?',
    'auth.tagline': 'Tu camino de salud mental comienza aquí',
    'auth.communityTagline': 'Únete a nuestra comunidad de bienestar mental',
    'auth.roleQuestion': 'Me registro como:',
    'auth.patientRole': 'Paciente',
    'auth.therapistRole': 'Terapeuta',
    'auth.haveAccount': '¿Ya tienes una cuenta?',
    'auth.passwordMismatch': 'Las contraseñas no coinciden',
    'auth.networkError': 'Error de red. Inténtalo de nuevo.',
    'auth.createJourney': 'Crea tu cuenta para comenzar tu viaje',
    'auth.resetInstructions': 'Ingresa tu correo para restablecer tu contraseña',
    'auth.continueGoogle': 'Continuar con Google',
    'auth.email': 'Correo electrónico',
    'auth.password': 'Contraseña',
    'auth.confirmPassword': 'Confirmar contraseña',
    'auth.signIn': 'Iniciar sesión',
    'auth.signUp': 'Registrarse',
    'auth.createAccountCta': '¿No tienes cuenta? Regístrate',
    'auth.orEmail': 'O continúa con email',
    'auth.therapistPortal': 'Portal de terapeutas',
    'auth.areTherapist': '¿Eres terapeuta? Haz clic aquí',
    'auth.noAccount': '¿No tienes cuenta?',
    'auth.forgotPassword': '¿Olvidaste tu contraseña?',
    'auth.patientJourney': 'Inicia sesión para continuar tu camino',
    'auth.therapistJourney': 'Inicia sesión para acceder a tu panel profesional',
    'auth.googleDisclaimer': 'Estamos trabajando hacia el cumplimiento HIPAA; evita compartir PHI.',
    'auth.firstName': 'Nombre',
    'auth.lastName': 'Apellido',
    'auth.backToSignIn': 'Volver a iniciar sesión',
    'auth.checkEmail': 'Revisa tu correo',
    'auth.resetEmailSent': 'Si existe una cuenta con {email}, enviamos instrucciones para restablecer la contraseña.',
    'auth.resetEmailBody': 'Revisa tu correo y haz clic en el enlace para crear una nueva contraseña. El enlace expira en 1 hora.',
    'auth.invalidCredentials': 'Correo o contraseña inválidos',
    'auth.verifyEmailFirst': 'Primero verifica tu correo. Revisa tu bandeja de entrada para el enlace de verificación.',
    // Contact therapist
    'contact.title': 'Contactar terapeuta',
    'contact.subtitle': 'Conéctate con tu terapeuta o descarga tus datos de ansiedad para consulta profesional',
    'contact.question': '¿Actualmente tienes un terapeuta?',
    'contact.questionDesc': 'Si tienes terapeuta, podemos conectar tu cuenta para que sigan tu progreso y te den mejor apoyo.',
    'contact.optionYes': 'Sí, quiero conectar a mi terapeuta',
    'contact.optionYesDesc': 'Envíale una solicitud segura para revisar tu progreso.',
    'contact.optionNo': 'No tengo terapeuta',
    'contact.optionNoDesc': 'Descarga tus datos o explora opciones profesionales.',
    'contact.connectTitle': 'Conecta con tu terapeuta',
    'contact.connectDesc': 'Ingresa el correo de tu terapeuta para enviarle una solicitud de conexión',
    'contact.emailLabel': 'Correo del terapeuta',
    'contact.emailPlaceholder': 'terapeuta@ejemplo.com',
    'contact.messageLabel': 'Mensaje (opcional)',
    'contact.messagePlaceholder': 'Cuéntale a tu terapeuta tus inquietudes actuales...',
    'contact.sendRequest': 'Enviar solicitud de conexión',
    'contact.connecting': 'Conectando...',
    'contact.back': 'Volver',
    'contact.selfGuidedTitle': 'Estás en modo autoguiado',
    'contact.selfGuidedDesc': 'Sigue usando la app para manejar la ansiedad. Considera conectar con un terapeuta para apoyo profesional.',
    'contact.downloadTitle': 'Descarga tus datos de ansiedad',
    'contact.downloadDesc': 'Obtén tu historial completo y resúmenes para compartir con un profesional de salud mental',
    'contact.packageTitle': 'Tu paquete de datos incluye:',
    'contact.packageItem1': 'Historial completo y tendencias de ansiedad',
    'contact.packageItem2': 'Resúmenes de conversación con la IA',
    'contact.packageItem3': 'Análisis de detonantes y patrones',
    'contact.packageItem4': 'Progreso de metas y resultados de intervenciones',
    'contact.packageItem5': 'Resultados de evaluaciones clínicas',
    'contact.downloadCta': 'Descargar mis datos',
    'contact.backOptions': 'Volver a opciones',
    'contact.readyTitle': '¿Listo para encontrar un terapeuta?',
    'contact.readyDesc': 'La terapia profesional puede mejorar significativamente tu manejo de la ansiedad',
    'contact.benefitsTitle': 'Beneficios de la terapia profesional:',
    'contact.benefit1': 'Planes de tratamiento personalizados a tus necesidades',
    'contact.benefit2': 'Enfoques terapéuticos basados en evidencia (CBT, DBT, etc.)',
    'contact.benefit3': 'Apoyo y respuesta profesional en crisis',
    'contact.benefit4': 'Manejo de medicación cuando corresponde',
    'contact.benefit5': 'Recuperación y estrategias de afrontamiento a largo plazo',
    'contact.findTherapist': 'Buscar terapeutas cerca de mí',
    'contact.downloadStarted': 'Descarga iniciada',
    'contact.downloadStartedDesc': 'Descargando tus datos de ansiedad y resúmenes de conversación...',
    'contact.downloadError': 'Error de descarga',
    'contact.downloadErrorDesc': 'No se pudieron descargar los datos de ansiedad',
    'contact.emailRequired': 'Correo requerido',
    'contact.emailRequiredDesc': 'Ingresa el correo electrónico de tu terapeuta',
    'contact.requestSent': 'Solicitud enviada',
    'contact.requestSentDesc': 'Tu terapeuta recibirá una notificación para aprobar la conexión',
    'contact.requestError': 'Error de conexión',
    'contact.requestErrorDesc': 'No se pudo conectar con el terapeuta. Inténtalo de nuevo.',
    'contact.emergencyTitle': 'Recursos de emergencia',
    'contact.emergency1': 'Línea Nacional de Prevención del Suicidio',
    'contact.emergency1Desc': 'Apoyo en crisis 24/7',
    'contact.emergency2': 'Línea de texto de crisis',
    'contact.emergency2Desc': 'Apoyo por texto disponible 24/7',
    'contact.emergency3': 'Línea nacional SAMHSA',
    'contact.emergency3Desc': 'Referencia a tratamiento e información',
    // Dashboard
    'dashboard.title': 'Panel',
    'dashboard.heroTitle': 'Guardia de Ansiedad',
    'dashboard.heroSubtitle': 'Tu compañero de apoyo para la ansiedad con IA. Obtén orientación personalizada, sigue tu progreso y encuentra tranquilidad cuando la necesites.',
    'dashboard.startChatting': 'Comenzar chat',
    'dashboard.takeAssessment': 'Tomar evaluación',
    'dashboard.trackTreatment': 'Seguimiento/Tratamiento',
    'dashboard.analytics': 'Analítica',
    'dashboard.feature.safe': 'Seguro y privado',
    'dashboard.feature.safeDesc': 'Tus conversaciones son completamente privadas y seguras',
    'dashboard.feature.support': 'Soporte 24/7',
    'dashboard.feature.supportDesc': 'Siempre disponible cuando necesites hablar',
    'dashboard.feature.personalized': 'Cuidado personalizado',
    'dashboard.feature.personalizedDesc': 'Apoyo adaptado a tus necesidades únicas',
    'dashboard.footer.rights': 'Todos los derechos reservados.',
    'dashboard.footer.privacy': 'Política de privacidad',
    'dashboard.footer.terms': 'Términos de servicio',
    'dashboard.footer.contact': 'Contáctanos',
    'dashboard.footer.disclaimer': 'Esta app no sustituye el consejo, diagnóstico o tratamiento médico profesional. Siempre consulta con tu médico u otro profesional de salud calificado ante cualquier duda sobre una condición médica.',
    'dashboard.footer.version': 'Versión',
    // Settings
    'settings.title': 'Configuración',
    'settings.subtitle': 'Personaliza tu experiencia y administra tus preferencias.',
    'settings.account': 'Cuenta',
    'settings.accountDesc': 'Administra la información y configuración de tu cuenta.',
    'settings.currentEmail': 'Correo actual',
    'settings.notSignedIn': 'No has iniciado sesión',
    'settings.patientCode': 'Tu código de paciente',
    'settings.copy': 'Copiar',
    'settings.codeCopied': 'Código de paciente copiado',
    'settings.shareCodeHint': 'Comparte este código con tu terapeuta junto con tu correo para que acceda a tus analíticas y datos de tratamiento.',
    'settings.newEmail': 'Nuevo correo electrónico',
    'settings.newEmailPlaceholder': 'Ingresa nuevo correo',
    'settings.updateEmail': 'Actualizar correo',
    'settings.updating': 'Actualizando...',
    'settings.emailErrorTitle': 'Error',
    'settings.emailErrorDesc': 'Ingresa un correo diferente',
    'settings.emailUpdateError': 'Error al actualizar correo',
    'settings.emailUpdateErrorDesc': 'No se pudo actualizar el correo',
    'settings.emailRequestedTitle': 'Solicitud enviada',
    'settings.emailRequestedDesc': 'Revisa tus correos (el actual y el nuevo) para completar el cambio.',
    'settings.logout': 'Cerrar sesión',
    'settings.loggingOut': 'Cerrando sesión...',
    'settings.logoutSuccess': 'Sesión cerrada',
    'settings.logoutSuccessDesc': 'Has salido de tu cuenta.',
    'settings.logoutError': 'Error al cerrar sesión',
    'settings.logoutErrorDesc': 'No se pudo cerrar sesión',
    'settings.voiceLanguage': 'Voz e idioma',
    'settings.voiceLanguageDesc': 'Configura cómo la IA habla y responde.',
    'settings.languageLabel': 'Idioma',
    'settings.languagePlaceholder': 'Selecciona idioma',
    'settings.voiceResponses': 'Respuestas de voz',
    'settings.voiceResponsesDesc': 'Habilita que la IA hable en voz alta',
    'settings.voiceInterruption': 'Interrupción de voz',
    'settings.voiceInterruptionDesc': 'Permite interrumpir a la IA hablando',
    'settings.privacy': 'Privacidad y datos',
    'settings.privacyDesc': 'Controla cómo se almacenan y usan tus datos.',
    'settings.localStorage': 'Solo almacenamiento local',
    'settings.localStorageDesc': 'Mantén todos los datos en tu dispositivo',
    'settings.analytics': 'Permitir analíticas',
    'settings.analyticsDesc': 'Ayúdanos a mejorar compartiendo uso anonimizado',
    'settings.dailyCheckIns': 'Revisiones diarias',
    'settings.dailyCheckInsDesc': 'Recibe recordatorios de ánimo y ansiedad',
    'settings.breathingReminders': 'Recordatorios de respiración',
    'settings.breathingRemindersDesc': 'Recibe recordatorios para ejercicios de respiración',
    // Therapist portal (light)
    'therapistPortal.title': 'Portal de terapeutas',
    'therapistPortal.subtitle': 'Ingresa tu correo para acceder a los datos de progreso de tus pacientes',
    'therapistPortal.emailLabel': 'Correo electrónico',
    'therapistPortal.emailPlaceholder': 'dr.smith@ejemplo.com',
    'therapistPortal.access': 'Acceder al portal',
    'therapistPortal.verifying': 'Verificando...',
    'therapistPortal.demoNote': 'Nota demo:',
    'therapistPortal.demoBody': 'Ingresa cualquier correo que tus pacientes hayan usado para conectarse contigo. Este portal muestra las mismas analíticas y resultados que ven los pacientes.',
    'therapistPortal.emailRequired': 'Correo requerido',
    'therapistPortal.emailRequiredDesc': 'Ingresa tu correo electrónico',
    'therapistPortal.accessGranted': 'Acceso concedido',
    'therapistPortal.welcome': 'Bienvenido al portal de terapeutas',
    'therapistPortal.errorTitle': 'Error',
    'therapistPortal.errorDesc': 'No se pudo verificar el acceso',
    'therapistPortal.searchRequired': 'Búsqueda requerida',
    'therapistPortal.searchRequiredDesc': 'Ingresa el correo o código de 6 dígitos del paciente',
    'therapistPortal.noPatients': 'No se encontraron pacientes',
    'therapistPortal.noPatientsDesc': 'No se hallaron pacientes con los criterios ingresados',
    'therapistPortal.searchComplete': 'Búsqueda completa',
    'therapistPortal.searchError': 'No se pudo buscar pacientes',
    // Notifications
    'notifications.title': 'Notificaciones',
    'notifications.back': 'Volver al panel',
    'notifications.new': 'nuevas',
    'notifications.markAll': 'Marcar todas como leídas',
    'notifications.emptyTitle': 'Sin notificaciones',
    'notifications.emptyDesc': '¡Estás al día! Vuelve más tarde para actualizaciones.',
    'notifications.markRead': 'Marcar como leída',
    'notifications.type.anxiety': 'Alerta de ansiedad',
    'notifications.type.treatment': 'Actualización de tratamiento',
    'notifications.type.reminder': 'Recordatorio',
    'notifications.type.achievement': 'Logro',
    'notifications.action.chat': 'Hablar con la IA',
    'notifications.action.track': 'Registrar tu ánimo',
    'notifications.action.progress': 'Ver progreso',
    'notifications.action.chatHistory': 'Ver historial de chat',
    'notifications.action.reschedule': 'Reprogramar',
    'notifications.action.view': 'Ver detalles',
    'notifications.msg.anxiety': 'Tus niveles de ansiedad han estado elevados los últimos 3 días. Considera ejercicios de respiración o hablar con tu terapeuta.',
    'notifications.msg.achievement': '¡Buen trabajo! Llevas 7 días seguidos registrando tu estado de ánimo. Sigue así.',
    'notifications.msg.reminder': 'Tienes una sesión programada para mañana a las 2:00 PM. No olvides preparar tus notas.',
    'notifications.msg.treatment': 'Es momento de tu revisión semanal. ¿Cómo te sientes esta semana?',
    // Help
    'help.title': 'Centro de ayuda',
    'help.faqTitle': 'Preguntas frecuentes',
    'help.faqDesc': 'Encuentra respuestas a preguntas comunes sobre cómo usar la aplicación',
    'help.q1': '¿Cómo funciona el compañero de IA?',
    'help.a1': 'El compañero de IA usa procesamiento de lenguaje natural para brindar apoyo personalizado en el manejo de ansiedad. Puede conversar, ofrecer estrategias y ayudarte a seguir tu bienestar emocional.',
    'help.q2': '¿Mis datos son privados y seguros?',
    'help.a2': 'Sí, tu privacidad es prioridad. Las conversaciones y datos personales están cifrados y almacenados de forma segura. Tienes control total sobre tus datos.',
    'help.q3': '¿Puedo usar la app sin terapeuta?',
    'help.a3': 'Puedes usarla de forma independiente para manejo diario de ansiedad, aunque recomendamos consultar a un profesional de salud mental para cuidado integral.',
    'help.contactTitle': 'Contactar soporte',
    'help.contactDesc': '¿No encuentras lo que buscas? Escribe a nuestro equipo de soporte.',
    'help.contactBody': 'Si tienes preguntas no respondidas en el FAQ, contáctanos. Respondemos normalmente en 24 horas.',
    'help.contactEmailLabel': 'Correo',
    'help.contactEmail': 'support@anxietycompanion.com',
    // Support page (about/help)
    'support.title': 'Centro de soporte',
    'support.subtitle': 'Obtén ayuda con Tranquiloo y recursos de salud mental',
    'support.backSettings': 'Volver a Configuración',
    'support.contactTeam': 'Contacta a nuestro equipo de soporte',
    'support.contactBody': 'Nuestro equipo está para ayudarte con dudas técnicas o de uso. Respondemos a tiempo para darte la mejor experiencia.',
    'support.emailSupport': 'Soporte por correo',
    'support.emailDesc': 'Envíanos un mensaje y respondemos en 24 horas.',
    'support.emailCta': 'Enviar correo',
    'support.phoneSupport': 'Soporte telefónico',
    'support.phoneDesc': 'Habla con nuestro equipo para ayuda inmediata.',
    'support.callNow': 'Llamar ahora',
    'support.textSupport': 'Soporte por texto',
    'support.textDesc': 'Envía un mensaje para preguntas rápidas o no urgentes.',
    'support.textAvailability': 'Disponible 24/7 para soporte no urgente',
    'support.crisisTitle': 'Apoyo en crisis y recursos de emergencia',
    'support.crisisLead': 'Si estás en crisis o tienes pensamientos de autolesión:',
    'support.nationalResources': 'Recursos nacionales',
    'support.onlineResources': 'Recursos en línea',
    'support.faqTitle': 'Preguntas frecuentes',
    'support.faq1.q': '¿Cómo restablezco mi contraseña?',
    'support.faq1.a': 'Ve a la página de inicio de sesión y haz clic en "Olvidé mi contraseña". Ingresa tu correo y te enviaremos un enlace seguro.',
    'support.faq2.q': '¿Mis datos son seguros y privados?',
    'support.faq2.a': 'Trabajamos para el cumplimiento total y usamos cifrado para proteger tu información. Revisa la Política de privacidad para más detalles.',
    'support.faq3.q': '¿Puedo exportar mi historial de conversaciones?',
    'support.faq3.a': 'Puedes descargar resúmenes de conversación y datos de analítica desde las secciones de Analítica y Recursos de tratamiento.',
    'support.faq4.q': '¿Qué tan preciso es el análisis de ansiedad con IA?',
    'support.faq4.a': 'La IA sigue marcos clínicos de evaluación, pero complementa—no reemplaza—la atención profesional. Consulta a profesionales de salud para decisiones clínicas.',
    'support.faq5.q': '¿Puedo usar Tranquiloo con mi terapeuta?',
    'support.faq5.a': 'Sí. Comparte analíticas e informes de progreso con tu terapeuta usando la función “Compartir con terapeuta”.',
    'support.faq6.q': '¿Cómo puede mi terapeuta ver mis datos de progreso?',
    'support.faq6.a': 'Después de conectarlo en la app, puede acceder a su portal para ver analíticas en tiempo real e informes semanales.',
    // Therapist dashboard / patient directory
    'therapistDashboard.patientDirectory': 'Directorio de pacientes',
    'therapistDashboard.patientDirectoryDesc': 'Todos tus pacientes aceptados ({count} en total)',
    'therapistDashboard.searchPlaceholder': 'Buscar por nombre, correo o código de paciente...',
    'therapistDashboard.loadingPatients': 'Cargando directorio de pacientes...',
    'therapistDashboard.noPatients': 'Aún no hay pacientes',
    'therapistDashboard.noPatientsSearch': 'No se encontraron pacientes con tu búsqueda',
    'therapistDashboard.active': 'Activo',
    'therapistDashboard.sharingReports': 'Compartiendo reportes',
    'therapistDashboard.email': 'Correo',
    'therapistDashboard.patientCode': 'Código de paciente',
    'therapistDashboard.phone': 'Teléfono',
    'therapistDashboard.gender': 'Género',
    'therapistDashboard.age': 'Edad',
    'therapistDashboard.connected': 'Conectado',
    'therapistDashboard.years': 'años',
    'therapistDashboard.downloads.title': 'Tendencias de descargas',
    'therapistDashboard.downloads.noneTitle': 'Sin historial de descargas',
    'therapistDashboard.downloads.noneDesc': 'Aquí verás tu actividad de descargas cuando exportes reportes, gráficos y datos de analítica. Cada descarga se registrará con detalles.',
    'therapistDashboard.downloads.total': 'Total de descargas',
    'therapistDashboard.downloads.totalData': 'Datos totales',
    'therapistDashboard.downloads.thisWeek': 'Esta semana',
    'therapistDashboard.downloads.avgSize': 'Tamaño promedio',
    'therapistDashboard.downloads.activity': 'Actividad de descargas',
    'therapistDashboard.downloads.category': 'Mezcla de categorías de descarga',
    'therapistDashboard.downloads.types.analytics': 'Analíticas',
    'therapistDashboard.downloads.types.reports': 'Reportes',
    'therapistDashboard.downloads.types.summaries': 'Resúmenes',
    'therapistDashboard.downloads.types.exports': 'Exportaciones',
    'therapistDashboard.range.allTime': 'Todo el tiempo',
    'therapistDashboard.range.select': 'Selecciona un rango',
    'therapistDashboard.range.label': 'Rango de fechas',
    'therapistDashboard.range.apply': 'Aplicar',
    'therapistDashboard.range.clear': 'Limpiar',
    // Analytics header
    'analytics.header.title': 'Panel de analíticas',
    'analytics.header.data': 'Mostrando datos de {count} sesiones de análisis de ansiedad',
    'analytics.header.empty': 'Aún no hay datos; inicia un chat para ver analíticas',
    'analytics.header.downloadHistory': 'Descargar historial',
    'analytics.header.downloadSummary': 'Descargar resumen de conversación',
    'analytics.header.shareTherapist': 'Compartir con terapeuta',
    'analytics.header.viewTreatment': 'Ver tratamiento',
    'analytics.header.realtime': 'Datos en tiempo real',
    // Analytics metrics
    'analytics.metrics.totalSessions': 'Sesiones totales',
    'analytics.metrics.averageAnxiety': 'Ansiedad promedio',
    'analytics.metrics.mostCommonTrigger': 'Disparador más común',
    'analytics.metrics.noTriggers': 'Sin disparadores registrados',
    'analytics.metrics.treatmentProgress': 'Progreso del tratamiento',
    'analytics.metrics.progressImproving': 'Mejorando',
    // Analytics empty
    'analytics.empty.title': 'Aún no hay datos de analíticas',
    'analytics.empty.desc': 'Comienza a chatear con tu compañera de IA para generar datos de analítica de ansiedad.',
    'analytics.empty.start': 'Iniciar chat',
    // Analytics charts
    'analytics.trends.title': 'Tendencias semanales por tipo de ansiedad',
    'analytics.trends.none': 'Aún no hay datos de tendencias',
    'analytics.trends.work': 'Trabajo/Carrera',
    'analytics.trends.social': 'Social',
    'analytics.trends.health': 'Salud',
    'analytics.trends.financial': 'Finanzas',
    'analytics.trends.relationships': 'Relaciones',
    'analytics.trends.future': 'Futuro/Incertidumbre',
    'analytics.trends.family': 'Familia',
    'analytics.triggers.title': 'Análisis de detonantes',
    'analytics.triggers.total': 'Entradas totales: {count}',
    'analytics.triggers.trigger': 'Detonante',
    'analytics.triggers.count': 'Cantidad',
    'analytics.triggers.avgSeverity': 'Severidad prom.',
    'analytics.triggers.trend': 'Tendencia',
    'analytics.triggers.related': 'Detonantes relacionados',
    'analytics.triggers.why': 'Por qué sucede',
    'analytics.triggers.description': 'Descripción',
    'analytics.triggers.evidence': 'Evidencia clínica',
    'analytics.triggers.trendLabel': 'Tendencia',
    'analytics.triggers.recalledContext': 'Contexto recordado',
    'analytics.triggers.aggravators': 'Factores que agravan',
    'analytics.triggers.impact': 'Impacto/Evitación',
    'analytics.triggers.lastOccurrence': 'Última ocurrencia',
    'analytics.triggers.relatedPatterns': 'Patrones de detonantes relacionados',
    // Anxiety tracker
    'analytics.tracker.title': 'Tus analíticas y seguimiento de ansiedad',
    'analytics.tracker.emptyTitle': 'Analítica y seguimiento de ansiedad',
    'analytics.tracker.emptyDesc': 'Comienza a chatear para ver analíticas y seguimiento de intervenciones.',
    'analytics.tracker.startChat': 'Iniciar sesión de chat',
    'analytics.tracker.avgAnxiety': 'Ansiedad promedio',
    'analytics.tracker.avgGad7': 'GAD-7 promedio',
    'analytics.tracker.sessions': 'Sesiones',
    'analytics.tracker.trend': 'Tendencia',
    'analytics.tracker.mostEffective': 'Intervenciones más efectivas para ti:',
    'analytics.tracker.effectiveness': 'efectividad',
    'analytics.tracker.used': 'Usado {count}x',
    'analytics.tracker.recentProgress': 'Tu progreso reciente:',
    'analytics.tracker.progressImproving': '🎉 ¡Gran progreso! Tus niveles de ansiedad han disminuido. Sigue usando las intervenciones que mejor te funcionan.',
    'analytics.tracker.progressStable': '📊 Tus niveles de ansiedad están estables. Considera probar nuevas intervenciones o aumentar la frecuencia de las actuales.',
    'analytics.tracker.progressWorsening': '🤗 Tus niveles de ansiedad han aumentado recientemente. Es normal; considera buscar apoyo adicional o usar intervenciones de crisis.',
    // Treatment outcomes
    'analytics.outcomes.title': 'Resultados del tratamiento',
    'analytics.outcomes.emptyDesc': 'Comienza a seguir tu ansiedad para ver resultados y tendencias.',
    'analytics.outcomes.anxietyLevel': 'Nivel de ansiedad',
    // Monthly charts
    'analytics.monthly.title': 'Tendencias mensuales por categoría',
    'analytics.monthly.none': 'Agrega más sesiones para ver tendencias mensuales.',
    // Chat history
    'chatHistory.title': 'Historial de chat',
    'chatHistory.subtitle': 'Revisa tus conversaciones e intervenciones previas',
    'chatHistory.recentConversations': 'Conversaciones recientes',
    'chatHistory.sessionsDesc': 'Tus sesiones de chat con las compañeras de IA',
    'chatHistory.analyticsTitle': 'Análisis de ansiedad',
    'chatHistory.analyticsDesc': 'Análisis generados por IA de tus chats',
    'chatHistory.low': 'Bajo',
    'chatHistory.moderate': 'Moderado',
    'chatHistory.high': 'Alto',
    'chatHistory.noSessions': 'Aún no hay sesiones de chat',
    'chatHistory.noSessionsDesc': 'Comienza una conversación para ver tu historial aquí',
    'chatHistory.untitled': 'Chat sin título',
    'chatHistory.viewConversation': 'Ver conversación',
    'chatHistory.anxietyLevel': 'Nivel de ansiedad',
    'chatHistory.interventions': 'Intervenciones de ansiedad',
    'chatHistory.interventionsDesc': 'Análisis de ansiedad y estrategias de afrontamiento impulsadas por IA',
    'chatHistory.noAnalyses': 'Aún no hay análisis de ansiedad',
    'chatHistory.noAnalysesDesc': 'Chatea con nuestras compañeras de IA para recibir apoyo personalizado',
    // Appointments
    'appointments.back': 'Volver',
    'appointments.title': 'Mis citas',
    'appointments.subtitle': 'Programa y gestiona tus sesiones de terapia',
    // Goals
    'analytics.goals.title': 'Resumen de progreso de metas',
    'analytics.goals.emptyTitle': 'Aún no hay metas',
    'analytics.goals.emptyDesc': 'Crea metas para seguir tu progreso y ver analíticas.',
    'analytics.goals.total': 'Metas',
    'analytics.goals.completed': 'Completadas',
    'analytics.goals.inProgress': 'En progreso',
    'analytics.goals.avgScore': 'Puntaje prom.',
    'analytics.goals.adherence': 'Adherencia',
    'analytics.goals.history': 'Historial de progreso',
    'analytics.goals.category': 'Categoría',
    'analytics.goals.badge.completed': 'Completada',
    'analytics.goals.badge.good': 'Buen progreso',
    'analytics.goals.badge.started': 'Comenzando',
    'analytics.goals.badge.new': 'Meta nueva',
    'analytics.goals.progressLabel': 'Progreso',
    'analytics.goals.scoreLabel': 'Puntaje',
    // Treatment outcomes charts
    'analytics.outcomes.trendTitle': 'Tendencias del nivel de ansiedad promedio',
    'analytics.outcomes.trendEmptyTitle': 'Aún no hay datos de tendencias',
    'analytics.outcomes.trendEmptyDesc': 'Comienza a registrar tus niveles de ansiedad para ver tendencias de progreso',
    'analytics.outcomes.weeklyTitle': 'Resultados semanales del tratamiento',
    'analytics.outcomes.avgAnxiety': 'Ansiedad prom.',
    'analytics.outcomes.trendLabel': 'Tendencia',
    'analytics.outcomes.treatmentEffectiveness': 'Efectividad del tratamiento',
    // Notifications
    'notifications.title': 'Notificaciones',
    'notifications.back': 'Volver al panel',
    'notifications.new': 'nuevas',
    'notifications.title': 'Notificaciones',
    'notifications.back': 'Volver al panel',
    'notifications.new': 'nuevas',
    'notifications.markAll': 'Marcar todas como leídas',
    'notifications.emptyTitle': 'Sin notificaciones',
    'notifications.emptyDesc': '¡Estás al día! Vuelve más tarde para actualizaciones.',
    'notifications.markRead': 'Marcar como leída',
    'notifications.type.anxiety': 'Alerta de ansiedad',
    'notifications.type.treatment': 'Actualización de tratamiento',
    'notifications.type.reminder': 'Recordatorio',
    'notifications.type.achievement': 'Logro',
    'notifications.action.chat': 'Hablar con la IA',
    'notifications.action.track': 'Registrar tu ánimo',
    'notifications.action.progress': 'Ver progreso',
    'notifications.action.chatHistory': 'Ver historial de chat',
    'notifications.action.reschedule': 'Reprogramar',
    'notifications.action.view': 'Ver detalles',
    // Therapist auth
    'therapist.title.signin': 'Portal profesional',
    'therapist.title.signup': 'Únete a nuestra red profesional',
    'therapist.subtitle.signin': 'Inicia sesión para acceder a tu panel profesional',
    'therapist.subtitle.signup': 'Crea tu cuenta profesional para conectar con pacientes',
    'therapist.immediateAccess': 'Acceso inmediato',
    'therapist.immediateAccess.desc': 'Puedes usar el panel mientras verificamos tu licencia en segundo plano',
    'therapist.licenseNumber': 'Número de licencia',
    'therapist.specialty': 'Especialidad',
    'therapist.yearsExperience': 'Años de experiencia',
    'therapist.applyNow': '¿No tienes cuenta profesional? Solicítala aquí',
  },
};

interface LanguageContextValue {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, fallback?: string) => string;
}

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    const saved = localStorage.getItem('app_language') as Language | null;
    if (saved === 'en' || saved === 'es') {
      setLanguageState(saved);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('app_language', lang);
  };

  const t = useMemo(() => {
    return (key: string, fallback?: string) => {
      const value = translationMap[language]?.[key];
      if (value) return value;
      const defaultVal = translationMap.en[key];
      return defaultVal || fallback || key;
    };
  }, [language]);

  const value = useMemo(() => ({ language, setLanguage, t }), [language, setLanguage, t]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return ctx;
};
